// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0T-j9YxgL9_kAB_Z-jWQfPeNX1hLiMfE',
    appId: '1:405740710757:web:dc514dd35eb5f096540f8c',
    messagingSenderId: '405740710757',
    projectId: 'my-first-project-9ad78',
    authDomain: 'my-first-project-9ad78.firebaseapp.com',
    storageBucket: 'my-first-project-9ad78.appspot.com',
    measurementId: 'G-PH7VPQECS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0jviX6ea7a3somapYtbYCnsuKL6BfJuI',
    appId: '1:405740710757:android:753a120f0ebbb8bc540f8c',
    messagingSenderId: '405740710757',
    projectId: 'my-first-project-9ad78',
    storageBucket: 'my-first-project-9ad78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASOfPvpZ-B7I1tYSN266sX2KsNORl-ahY',
    appId: '1:405740710757:ios:b68205636aef98da540f8c',
    messagingSenderId: '405740710757',
    projectId: 'my-first-project-9ad78',
    storageBucket: 'my-first-project-9ad78.appspot.com',
    iosBundleId: 'com.example.formValidationUiDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0T-j9YxgL9_kAB_Z-jWQfPeNX1hLiMfE',
    appId: '1:405740710757:web:160042e28e94b62b540f8c',
    messagingSenderId: '405740710757',
    projectId: 'my-first-project-9ad78',
    authDomain: 'my-first-project-9ad78.firebaseapp.com',
    storageBucket: 'my-first-project-9ad78.appspot.com',
    measurementId: 'G-W18QEY83P7',
  );
}
